# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/unicornslayer/Projects/summerSchoolPersonal/Day00/Ex03_DungeonCrawl/src/Game/CMakeLists.txt))

/Users/unicornslayer/Projects/summerSchoolPersonal/Day00/Ex03_DungeonCrawl/build_xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.11.4/bin/cmake -H/Users/unicornslayer/Projects/summerSchoolPersonal/Day00/Ex03_DungeonCrawl -B/Users/unicornslayer/Projects/summerSchoolPersonal/Day00/Ex03_DungeonCrawl/build_xcode
